root: ./

structure: 
  readme: README.md
  summary: SUMMARY.md

redirects: 
  other/events : ./tutorials/advanced-development/promise-events/promise-events.md
  other/more-modules : ./tutorials/core-concepts/modules/more-modules.md
  other/nunjucks-filters : ./tutorials/core-concepts/working-with-templates/nunjucks-filters.md
  tutorials/howtos/trim-index : ./tutorials/advanced-development/advanced-pieces-topics/next-previous-links.md
  tutorials/howtos/hide-index-page : ./tutorials/advanced-development/advanced-pieces-topics/next-previous-links.md
  tutorials/howtos/what-to-do-when-you-are-locked-out-of-apostrophe : ./tutorials/core-concepts/users-and-permissions/user-login-and-password.md
  tutorials/howtos/apostrophe-i18n-config : ./tutorials/advanced-development/internationalization-localization/apostrophe-i18n-config.md
  tutorials/howtos/nested-module-folders : ./tutorials/core-concepts/modules/nested-module-folders.md
  technical-overviews/technical-overview : ./tutorials/core-concepts/technical-overview.md
  technical-overviews/how-apostrophe-starts-up : ./tutorials/advanced-development/how-apostrophe-starts-up.md
  technical-overviews/how-apostrophe-handles-requests : ./tutorials/advanced-development/how-apostrophe-handles-requests.md
  technical-overviews/how-apostrophe-modules-are-structured : ./tutorials/core-concepts/modules/how-apostrophe-modules-are-structured.md
  core-concepts/reusable-content-pieces/children-joins : ./tutorials/core-concepts/reusable-content-pieces/joins.md
  tutorials/howtos/storing-images-and-files-in-amazon-s3 : ./tutorials/devops/cloud/storing-images-and-files-in-amazon-s3.md
  tutorials/howtos/storing-images-and-files-in-azure-blob-storage : ./tutorials/devops/cloud/storing-images-and-files-in-azure-blob-storage.md
  tutorials/howtos/storing-images-and-files-in-google-cloud-storage : ./tutorials/devops/cloud/storing-images-and-files-in-google-cloud-storage.md
  tutorials/howtos/migration : ./tutorials/devops/migration.md
  tutorials/howtos/linode : ./tutorials/devops/deployment/linode.md
  tutorials/howtos/deploying-apostrophe-in-the-cloud-with-heroku : ./tutorials/devops/deployment/deploying-apostrophe-in-the-cloud-with-heroku.md
  tutorials/howtos/deploying-apostrophe-in-the-cloud-with-aws : ./tutorials/devops/deployment/deploying-apostrophe-in-the-cloud-with-aws.md
  tutorials/howtos/multicore : ./tutorials/devops/multicore.md
  tutorials/howtos/windows : ./tutorials/devops/windows.md
  tutorials/howtos/docker :  ./tutorials/devops/docker.md
  tutorials/howtos/replica-set : ./tutorials/advanced-development/database/replica-set.md
  tutorials/howtos/storing-sessions-in-redis : ./tutorials/devops/storing-sessions-in-redis.md
  tutorials/howtos/next-and-previous-pieces : ./tutorials/core-concepts/reusable-content-pieces/browsing-directory-of-pieces.md
  tutorials/howtos/adding-fields-to-all-pieces : ./tutorials/advanced-development/advanced-pieces-topics/adding-fields-to-all-pieces.md
  tutorials/howtos/lean-frontend-assets : ./tutorials/core-concepts/front-end-assets/lean-frontend-assets.md
  tutorials/howtos/adding-new-batch-operations : ./tutorials/advanced-development/advanced-pieces-topics/adding-new-batch-operations.md
  tutorials/howtos/extending-the-pieces-editor-modal : ./tutorials/advanced-development/advanced-pieces-topics/extending-the-pieces-editor-modal.md
  tutorials/howtos/children-and-joins : ./tutorials/advanced-development/advanced-pages-topics/children-and-joins.md
  tutorials/howtos/responsive-images : ./tutorials/core-concepts/front-end-assets/pushing-assets.md
  tutorials/getting-started/page-templates : ./tutorials/core-concepts/pages-and-navigation/page-templates.md
  tutorials/getting-started/editing-page-templates : ./tutorials/core-concepts/pages-and-navigation/page-templates.md
  tutorials/getting-started/adding-editable-content-to-pages : ./tutorials/core-concepts/pages-and-navigation/widgets-singletons-and-areas.md
  tutorials/getting-started/building-navigation : ./tutorials/core-concepts/pages-and-navigation/connecting-pages.md
  tutorials/getting-started/custom-widgets : ./tutorials/core-concepts/editable-content-on-pages/custom-widgets.md
