root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  tutorials/getting-started/page-templates : ./tutorials/core-concepts/pages-and-navigation/page-templates.md
  tutorials/getting-started/editing-page-templates : ./tutorials/core-concepts/pages-and-navigation/page-templates.md
  tutorials/getting-started/adding-editable-content-to-pages : ./tutorials/core-concepts/pages-and-navigation/widgets-singletons-and-areas.md
  tutorials/getting-started/building-navigation : ./tutorials/core-concepts/pages-and-navigation/connecting-pages.md
  tutorials/getting-started/custom-widgets : ./tutorials/core-concepts/editable-content-on-pages/custom-widgets.md
  tutorials/getting-started/global : ./tutorials/core-concepts/global/README.md
  tutorials/getting-started/pushing-assets : ./tutorials/core-concepts/front-end-assets/pushing-assets.md
  tutorials/getting-started/nunjucks-helper-functions : ./tutorials/core-concepts/working-with-templates/nunjucks-helper-functions.md
  tutorials/getting-started/layout-widgets : ./tutorials/core-concepts/editable-content-on-pages/layout-widgets.md
  tutorials/getting-started/reusable-content-with-pieces : ./tutorials/core-concepts/reusable-content-pieces/reusable-content-with-pieces.md
  tutorials/getting-started/settings : ./tutorials/core-concepts/global/settings.md
  tutorials/getting-started/schema-guide : ./tutorials/schema-guide/schema-guide.md
  
  tutorials/intermediate/README : ./tutorials/advanced-development/README
  tutorials/intermediate/permissions : ./tutorials/core-concepts/users-and-groups
  tutorials/intermediate/custom-schema-fields-for-pages : ./tutorials/advanced-development/custom-schema-fields-for-pages
  tutorials/intermediate/model-layer : ./tutorials/advanced-development/model-layer
  tutorials/intermediate/cursors : ./tutorials/advanced-development/cursors
  tutorials/intermediate/forms : ./tutorials/core-concepts/reusable-content-with-pieces
  tutorials/intermediate/command-line-tasks : ./tutorials/advanced-development/command-line-tasks
  tutorials/intermediate/accessing-the-database-directly : ./tutorials/advanced-development/accessing-the-database-directly
  tutorials/intermediate/custom-schema-field-types : ./tutorials/advanced-development/custom-schema-field-types
  tutorials/intermediate/deployment : 

  tutorials/howtos/thumbnails-and-areas-of-child-pages : ./tutorials/core-concepts/pushing-assets
  tutorials/howtos/password-reset : ./tutorials/core-concepts/user-login-and-password
  tutorials/howtos/search : ./tutorials/core-concepts/search
  tutorials/howtos/admin-bar : ./tutorials/advanced-development/admin-bar
  tutorials/howtos/children-and-joins : ./tutorials/core-concepts/children-and-joins
  tutorials/howtos/redirecting-after-login : ./tutorials/core-concepts/redirecting-after-login
  
  tutorials/howtos/next-and-previous-pieces : ./tutorials/core-concepts/browsing-directory-of-pieces
  tutorials/howtos/adding-fields-to-all-pieces : ./tutorials/advanced-development/adding-fields-to-all-pieces
  tutorials/howtos/lean-frontend-assets : ./tutorials/core-concepts/lean-frontend-assets
  tutorials/howtos/adding-new-batch-operations : ./tutorials/advanced-development/adding-new-batch-operations
  tutorials/howtos/extending-the-pieces-editor-modal : ./tutorials/advanced-development/extending-the-pieces-editor-modal
  tutorials/howtos/responsive-images : ./tutorials/core-concepts/pushing-assets
  
  tutorials/howtos/storing-images-and-files-in-amazon-s3 : ./tutorials/devops/storing-images-and-files-in-amazon-s3
  tutorials/howtos/storing-images-and-files-in-azure-blob-storage : ./tutorials/devops/storing-images-and-files-in-azure-blob-storage
  tutorials/howtos/storing-images-and-files-in-google-cloud-storage : ./tutorials/devops/storing-images-and-files-in-google-cloud-storage
  tutorials/howtos/migration : ./tutorials/devops/migration
  tutorials/howtos/linode : ./tutorials/devops/linode
  tutorials/howtos/deploying-apostrophe-in-the-cloud-with-heroku : ./tutorials/devops/deploying-apostrophe-in-the-cloud-with-heroku
  tutorials/howtos/deploying-apostrophe-in-the-cloud-with-aws : ./tutorials/devops/deploying-apostrophe-in-the-cloud-with-aws
  tutorials/howtos/multicore : ./tutorials/devops/multicore
  tutorials/howtos/windows : ./tutorials/devops/windows
  tutorials/howtos/docker :  ./tutorials/devops/docker
  tutorials/howtos/replica-set : ./tutorials/advanced-development/replica-set
  tutorials/howtos/storing-sessions-in-redis : ./tutorials/devops/storing-sessions-in-redis
  
  tutorials/howtos/trim-index : ./tutorials/advanced-development/next-previous-links
  tutorials/howtos/hide-index-page : ./tutorials/core-concepts/next-previous-links
  tutorials/howtos/what-to-do-when-you-are-locked-out-of-apostrophe : ./tutorials/core-concepts/user-login-and-password
  tutorials/howtos/apostrophe-i18n-config : ./tutorials/advanced-development/apostrophe-i18n-config
  tutorials/howtos/nested-module-folders : ./tutorials/advanced-development/nested-module-folders
  technical-overviews/technical-overview : ./tutorials/core-concepts/technical-overview
  technical-overviews/how-apostrophe-starts-up : ./tutorials/advanced-development/how-apostrophe-starts-up
  technical-overviews/how-apostrophe-handles-requests : ./tutorials/advanced-development/how-apostrophe-handles-requests
  technical-overviews/how-apostrophe-modules-are-structured : ./tutorials/advanced-development/how-apostrophe-modules-are-structured
  other/events : ./tutorials/advanced-development/promise-events
  other/nunjucks-filters : ./tutorials/core-concepts/nunjucks-filters

