#!/bin/bash

if [ -z "$ENV" ]; then
  echo "💁‍♀️ Usage: ENV=staging npm run deploy"
  echo "(or as appropriate)"
  echo
  rm -r ./dist
  exit 1
fi

read -p "THIS WILL CRUSH THE SITE'S CONTENT ON $ENV. Are you sure? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

if [ $ENV == "staging" ]
then
  ipAddress=34.207.22.194
elif [ $ENV == "production" ]
then
  echo "🚧 Under construction"
  exit 1
else
  echo "🤷‍♀️ Target unknown"
  exit 1
fi

rsync -av --delete --exclude '.git' --exclude '**/node_modules' ./ nodeapps@$ipAddress:/opt/static/apos-docs &&
echo "Synced up to $ENV"
