#!/bin/sh

habit &&
(
  cd _site &&
  sitemap-static --prefix=http://apostrophecms.org/docs/ > sitemap.xml &&
  perl -pi -e 's/index.html//g' sitemap.xml
) &&
rsync --delete -a _site/ apostro2@apostrophecms.org:/opt/stagecoach/apps/apostrophe-website/docs &&
echo "Done!"


