#!/bin/bash

(
  cd _api-reference-generator/ &&
  rm package-lock.json
  rm -rf node_modules
  rm -rf ../docs/reference/modules/ &&
  # Not optional, we need to be documenting the latest published release
  npm update &&
  node app apostrophe:generation &&
  node app documentation:generate &&
  cat ../_tip-ins/modules.md > ../docs/reference/modules/README.md
) &&
echo "Done!"
