#!/bin/sh

node_modules/habit/bin/habit &&
(
  cd _site &&
  sitemap-static --prefix=http://apostrophenow.org/ > sitemap.xml &&
  perl -pi -e 's/index.html//g' sitemap.xml
) &&
rsync --delete -a _site/ apostro2@45.56.109.144:/var/www/docs &&
echo "Done!"
